package com.zaryxstudios.okaso.world.structure;

import org.bukkit.Material;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.GZIPOutputStream;

public class NbtStructureWriter {

    private NbtStructureWriter() {}

    public static void write(BukkitStructure structure, String filePath) throws IOException {
        try (DataOutputStream out = new DataOutputStream(
                new BufferedOutputStream(
                new GZIPOutputStream(
                new FileOutputStream(filePath))))) {

            Map<String, Integer> paletteMap = new LinkedHashMap<>();
            List<String> paletteOrder = new ArrayList<>();
            Material[][][] blocks = structure.getRawBlocks();
            byte[][][] blockData = structure.getRawBlockData();
            List<int[]> blockEntries = new ArrayList<>();

            for (int x = 0; x < structure.getWidth(); x++) {
                for (int y = 0; y < structure.getHeight(); y++) {
                    for (int z = 0; z < structure.getLength(); z++) {
                        Material mat = blocks[x][y][z];
                        if (mat != null && mat != Material.AIR) {
                            String key = "minecraft:" + mat.name().toLowerCase();
                            if (!paletteMap.containsKey(key)) {
                                paletteMap.put(key, paletteMap.size());
                                paletteOrder.add(key);
                            }
                            blockEntries.add(new int[]{x, y, z, paletteMap.get(key)});
                        }
                    }
                }
            }

            out.writeByte(10);
            out.writeShort(0);

            writeNamedTag(out, (byte) 11, "size");
            out.writeInt(3);
            out.writeInt(structure.getWidth());
            out.writeInt(structure.getHeight());
            out.writeInt(structure.getLength());

            writeNamedTag(out, (byte) 9, "palette");
            out.writeByte(10); 
            out.writeInt(paletteOrder.size());
            for (String entry : paletteOrder) {
                out.writeByte(10);
                out.writeShort(0);
                writeStringTag(out, "Name", entry);
                out.writeByte(0);
            }

            writeNamedTag(out, (byte) 9, "blocks");
            out.writeByte(10);
            out.writeInt(blockEntries.size());
            for (int[] entry : blockEntries) {
                out.writeByte(10);
                out.writeShort(0);

                writeNamedTag(out, (byte) 11, "pos");
                out.writeInt(3);
                out.writeInt(entry[0]);
                out.writeInt(entry[1]);
                out.writeInt(entry[2]);

                writeNamedTag(out, (byte) 3, "state");
                out.writeInt(entry[3]);

                out.writeByte(0);
            }

            writeNamedTag(out, (byte) 9, "entities");
            out.writeByte(10);
            out.writeInt(0);

            out.writeByte(0);
            out.flush();
        }
    }

    public static void writeSimple(BukkitStructure structure, String filePath) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(
                new OutputStreamWriter(
                new FileOutputStream(filePath), StandardCharsets.UTF_8))) {

            writer.write("# Minecraft Structure Export");
            writer.newLine();
            writer.write("# Generated by Okaso Framework");
            writer.newLine();
            writer.write("WIDTH=" + structure.getWidth());
            writer.newLine();
            writer.write("HEIGHT=" + structure.getHeight());
            writer.newLine();
            writer.write("LENGTH=" + structure.getLength());
            writer.newLine();
            writer.write("BLOCKS=" + structure.getBlocks().size());
            writer.newLine();

            for (Object[] block : structure.getBlocks()) {
                int x = (int) block[0];
                int y = (int) block[1];
                int z = (int) block[2];
                Material mat = (Material) block[3];
                byte data = (byte) block[4];

                writer.write(x + "," + y + "," + z + "," +
                           "minecraft:" + mat.name().toLowerCase() + "," +
                           (data & 0xFF));
                writer.newLine();
            }
        }
    }

    
    private static void writeNamedTag(DataOutputStream out, byte tagType, String name) throws IOException {
        out.writeByte(tagType);
        writeString(out, name);
    }

    private static void writeStringTag(DataOutputStream out, String name, String value) throws IOException {
        writeNamedTag(out, (byte) 8, name);
        writeString(out, value);
    }

    private static void writeString(DataOutputStream out, String str) throws IOException {
        byte[] bytes = str.getBytes(StandardCharsets.UTF_8);
        out.writeShort(bytes.length);
        out.write(bytes);
    }
}
